name: Android CI Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      if: github.event_name != 'pull_request' && secrets.KEYSTORE != ''
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > release.keystore
        if [ ! -s release.keystore ]; then
          echo "Error: Decoded keystore is empty"
          exit 1
        fi

    - name: Get Version and Package ID
      id: get_info
      run: |
        VERSION=$(grep "versionName =" app/build.gradle.kts | awk -F '"' '{print $2}')
        PACKAGE_ID=$(grep "applicationId =" app/build.gradle.kts | awk -F '"' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "package_id=$PACKAGE_ID" >> $GITHUB_OUTPUT
        echo "filename=${PACKAGE_ID}-v${VERSION}.apk" >> $GITHUB_OUTPUT

    - name: Build Release APK
      if: github.event_name != 'pull_request' && secrets.KEYSTORE != ''
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: ../release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Rename APK
      if: github.event_name != 'pull_request' && secrets.KEYSTORE != ''
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${{ steps.get_info.outputs.filename }}

    - name: Build Debug APK
      if: github.event_name == 'pull_request' || secrets.KEYSTORE == ''
      run: ./gradlew assembleDebug

    - name: Upload Release Artifact
      if: github.event_name != 'pull_request' && secrets.KEYSTORE != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.get_info.outputs.filename }}
        path: app/build/outputs/apk/release/${{ steps.get_info.outputs.filename }}

    - name: Upload Debug Artifact
      if: github.event_name == 'pull_request' || (github.event_name != 'pull_request' && secrets.KEYSTORE == '')
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
